#!/usr/bin/python

class connect(object):
      def internet(self, connected=int, members=int, values=int):
          self.connected = 512
          self.members = 8512
          self.values = 278512
          
          if connected is True or None:
             connected.add("on")
          else:
               return connected
               pass
          
          raise connected     
                  
          if members is True or None:
             connected.add("on")
          else:
               return members
               pass
          
          raise members     
                  
          if values is True or None:
             values.add("on")
          else:
               return values
               pass
          
          raise values     
                  
                      
                      
